/* A packrat parser generated by PackCC 1.4.0 */

#ifndef PCC_INCLUDED_MAIN_H
#define PCC_INCLUDED_MAIN_H

typedef struct {
    const char *  filename;
    const char *  file;
    int     pos;
    int     size;

    int     line;
    int     linestart;
    int     prevlinestart;

    int     abort;
} State;


#define TYPE_IDENT          1
#define TYPE_LITERAL_NUMBER 2
#define TYPE_LITERAL_CHAR   3
#define TYPE_LITERAL_STRING 4
#define TYPE_LITERAL_BOOL   5
#define TYPE_LITERAL_ARRAY  6
#define TYPE_LITERAL_STRUCT 7
#define TYPE_EXPRESSION     8

typedef struct {
    const char *name;
} Ident;

typedef union {
    Ident ident;
} NodeV;

typedef struct {
    int     t;
    NodeV   v;
} Node;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct zz_context_tag zz_context_t;

zz_context_t *zz_create(State*auxil);
int zz_parse(zz_context_t *ctx, Node**ret);
void zz_destroy(zz_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_MAIN_H */
